"use strict";

const STORAGE_KEY = "qa-automation.bot-config";
const STEP_TYPES = {
  goto: { label: "Abrir URL", icon: "↗", target: "URL" }, click: { label: "Hacer click", icon: "⌁", target: "Selector, rol o texto" }, hover: { label: "Hacer hover", icon: "⌁", target: "Selector, rol o texto" },
  check: { label: "Marcar checkbox", icon: "☑", target: "Selector del checkbox" }, uncheck: { label: "Desmarcar checkbox", icon: "☐", target: "Selector del checkbox" },
  fill: { label: "Rellenar campo", icon: "✎", target: "Selector o label", value: "Valor" }, select: { label: "Seleccionar opción", icon: "▾", target: "Selector del campo", value: "Valor de la opción" },
  assert_text: { label: "Verificar texto", icon: "✓", target: "Selector o área", value: "Texto esperado" }, assert_url: { label: "Verificar URL", icon: "◉", target: "URL esperada" },
  wait: { label: "Esperar", icon: "◷", value: "Milisegundos" }, screenshot: { label: "Tomar screenshot", icon: "▣", value: "Nombre de evidencia" }, scroll: { label: "Hacer scroll", icon: "↕", target: "window", value: "Posición vertical (px)" },
};
const state = { config: { name: "", url: "", browser: "chromium", headless: true, steps: [] } };
const escapeHtml = (value) => String(value ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;");

function loadConfig() { try { const stored = JSON.parse(localStorage.getItem(STORAGE_KEY)); if (stored && Array.isArray(stored.steps)) state.config = { ...state.config, ...stored, headless: true }; } catch { localStorage.removeItem(STORAGE_KEY); } }
function readForm() { state.config.name = document.querySelector("#bot-name").value.trim(); state.config.url = document.querySelector("#bot-url").value.trim(); state.config.browser = document.querySelector("#bot-browser").value; state.config.headless = true; }
function writeForm() { document.querySelector("#bot-name").value = state.config.name; document.querySelector("#bot-url").value = state.config.url; document.querySelector("#bot-browser").value = state.config.browser; document.querySelector("#bot-headless").checked = true; }
function renderPreview() { document.querySelector("#bot-preview").textContent = JSON.stringify(state.config, null, 2); }

function renderSteps() {
  const container = document.querySelector("#bot-steps-list"); const count = state.config.steps.length; document.querySelector("#bot-step-count").textContent = `${count} ${count === 1 ? "paso" : "pasos"}`;
  if (!count) { container.innerHTML = `<div class="bot-empty"><div class="empty-icon">＋</div><strong>Aún no hay pasos</strong><span>Agrega manualmente las acciones del proceso.</span></div>`; renderPreview(); return; }
  container.innerHTML = state.config.steps.map((step, index) => { const definition = STEP_TYPES[step.type]; const details = [step.target && `Objetivo: ${step.target}`, step.value && `Valor: ${step.value}`].filter(Boolean).join(" · ") || "Sin parámetros adicionales"; return `<div class="bot-step-item"><div class="bot-step-number">${index + 1}</div><div class="bot-step-icon">${definition.icon}</div><div class="bot-step-content"><strong>${definition.label}</strong><span>${escapeHtml(details)}</span></div><div class="bot-step-actions"><button class="step-action" data-step-action="up" data-step-index="${index}" ${index === 0 ? "disabled" : ""}>↑</button><button class="step-action" data-step-action="down" data-step-index="${index}" ${index === count - 1 ? "disabled" : ""}>↓</button><button class="step-action danger" data-step-action="delete" data-step-index="${index}">×</button></div></div>`; }).join("");
  container.querySelectorAll("[data-step-action]").forEach((button) => button.addEventListener("click", () => { const index = Number(button.dataset.stepIndex); const action = button.dataset.stepAction; if (action === "delete") state.config.steps.splice(index, 1); else { const target = action === "up" ? index - 1 : index + 1; [state.config.steps[index], state.config.steps[target]] = [state.config.steps[target], state.config.steps[index]]; } renderSteps(); })); renderPreview();
}
function updateStepFields() { const definition = STEP_TYPES[document.querySelector("#bot-step-type").value]; const target = document.querySelector("#bot-step-target"); const value = document.querySelector("#bot-step-value"); target.disabled = !definition.target; value.disabled = !definition.value; target.placeholder = definition.target || "No aplica para este paso"; value.placeholder = definition.value || "No aplica para este paso"; document.querySelector("#bot-step-target-label").textContent = definition.target || "Objetivo"; document.querySelector("#bot-step-value-label").textContent = definition.value || "Valor"; }
function addStep(showToast) { const type = document.querySelector("#bot-step-type").value; const definition = STEP_TYPES[type]; const target = document.querySelector("#bot-step-target").value.trim(); const value = document.querySelector("#bot-step-value").value.trim(); if ((definition.target && !target) || (definition.value && !value)) return showToast(`Completa los datos del paso «${definition.label}».`, "error"); if (type === "wait" && (!Number.isFinite(Number(value)) || Number(value) <= 0)) return showToast("El tiempo debe ser mayor que cero.", "error"); state.config.steps.push({ type, target, value }); document.querySelector("#bot-step-target").value = ""; document.querySelector("#bot-step-value").value = ""; renderSteps(); showToast("Paso manual agregado al script.", "info"); }
function validateConfig(showToast) { readForm(); if (!state.config.name) return showToast("Escribe un nombre para el bot.", "error"); if (!/^https?:\/\//i.test(state.config.url)) return showToast("Indica una URL inicial válida.", "error"); if (!state.config.steps.length) return showToast("Agrega al menos un paso al script.", "error"); const validation = document.querySelector("#bot-validation"); validation.className = "bot-validation success"; validation.textContent = "✓ Script válido. Se ejecutará en segundo plano con Playwright."; showToast("Script validado correctamente.", "info"); return { ...state.config, steps: state.config.steps.map((step) => ({ ...step })) }; }

async function executeBot(showToast, runBot) { const config = validateConfig(showToast); if (!config) return; localStorage.setItem(STORAGE_KEY, JSON.stringify(config)); const button = document.querySelector("#bot-run"); const status = document.querySelector("#bot-run-status"); button.disabled = true; button.classList.add("loading"); status.className = "bot-run-status running"; status.innerHTML = "<strong>EJECUTANDO SCRIPT</strong><span>El proceso se ejecuta en segundo plano.</span>"; try { const result = await runBot(config); const passed = result.status === "PASS"; status.className = `bot-run-status ${passed ? "success" : "error"}`; status.innerHTML = `<strong>${passed ? "SCRIPT COMPLETADO" : "SCRIPT FALLIDO"}</strong><span>${escapeHtml(result.summary)} · ${escapeHtml(String(result.duration_seconds))} s</span><small>${result.steps.map((step) => `${step.status === "PASS" ? "✓" : "✕"} Paso ${step.step_number}: ${escapeHtml(step.message)}`).join("<br />")}</small>`; showToast(passed ? "Script completado correctamente." : "El script terminó con errores.", passed ? "info" : "error"); } catch (error) { status.className = "bot-run-status error"; status.innerHTML = `<strong>NO SE PUDO EJECUTAR</strong><span>${escapeHtml(error.message)}</span>`; showToast(error.message, "error"); } finally { button.disabled = false; button.classList.remove("loading"); } }
export function initializeBotModule({ showToast, runBot }) { loadConfig(); writeForm(); renderSteps(); updateStepFields(); document.querySelector("#bot-step-type").addEventListener("change", updateStepFields); document.querySelector("#bot-add-step").addEventListener("click", () => addStep(showToast)); document.querySelector("#bot-validate").addEventListener("click", () => validateConfig(showToast)); document.querySelector("#bot-run").addEventListener("click", () => executeBot(showToast, runBot)); document.querySelector("#bot-save").addEventListener("click", () => { readForm(); localStorage.setItem(STORAGE_KEY, JSON.stringify(state.config)); showToast("Script guardado en este equipo.", "info"); }); document.querySelector("#bot-clear").addEventListener("click", () => { state.config.steps = []; renderSteps(); showToast("Se quitaron los pasos del script.", "info"); }); }
